name: JMeter Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  jmeter-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List files in repo
        shell: powershell
        run: |
          Write-Host "Listing all files recursively:"
          Get-ChildItem -Path . -File -Recurse | Sort-Object FullName | ForEach-Object { Write-Host $_.FullName }

      - name: Set up JMeter
        shell: powershell
        run: |
          Invoke-WebRequest -Uri https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.zip -OutFile jmeter.zip
          Expand-Archive -Path jmeter.zip -DestinationPath .
          $env:PATH += ";${{ github.workspace }}\apache-jmeter-5.5\bin"
          Write-Host "JMeter path added to PATH"

      - name: Run JMeter Test
        shell: powershell
        run: |
          .\apache-jmeter-5.5\bin\jmeter.bat -n -t ".\tests\Test_Plan.jmx" -l results.jtl -j jmeter.log
